config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'homes#top'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top
  end

  def index
    @books = Book.all
    @book = Book.new()
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    if @book.save
      flash[:notice]="Book was successfully created."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def show
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    flash[:notice]="Book was successfully destroyed."
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<main>
<h1 class="title">Editing Book</h1>
<% if @book.errors.any? %>
  <div class="error">
  <%= @book.errors.count %> error prohibited this book from being saved:
  <ul>
  <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
  </div>
<% end %>
<%= form_with model: @book do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <span class="update-btn"><%= f.submit 'Update Book' %></span>

<% end %>
<div class="btn-field">
  <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
</div>
</main>

app/views/books/index.html.erb
<main>
<h1 class="title">Books</h1>
<div class="index">
  <table class="books">
  <tbody>
  <tr>
    <th>Title</th>
    <th>Body</th>
  </tr>
  <% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.body %></td>
    <td><%= link_to "Show", book_path(book.id) %></td>
    <td><%= link_to "Edit", edit_book_path(book.id) %></td>
    <td><%= link_to "Destroy", book_path(book.id), method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
  </tr>
  <% end %>
  </tbody>
  </table>
</div>
<div class="new-book">
  <h1>New book</h1>
  <% if @book.errors.any? %>
    <div class="error">
    <%= @book.errors.count %> errors prohibited this book from being saved:
    <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
    </div>
  <% end %>
  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>

    <h4>Body</h4>
    <%= f.text_area :body %>
    <span class="create-btn"><%= f.submit 'Create Book' %></span>

  <% end %>
</div>
</main>

app/views/books/show.html.erb
<main class="show">
<p><span class="bold">Title: </span><%= @book.title %></p>

<p><span class="bold">Body: </span><%= @book.body %></p>

<div class="btn-field">
  <%= link_to "Edit", edit_book_path %> | <%= link_to "Back", books_path %>
</div>
</main>

app/views/homes/top.html.erb
<main>
  <h1 class="title">ようこそBookersへ!</h1>
  <div class="top-content">
    <p class="top-text">
    Bookers では、さまざまな書籍に関するあなたの意見や<br>
    印象を共有し交換することができます
    </p>
    <span class="start-btn"><%= link_to "Start", books_path %></span>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>